// File generated by FlutterFire CLI.
// ignore_for_file: lines_longer_than_80_chars, avoid_classes_with_only_static_members
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyA4xZ9HhfycuXnfex97KHeP3MMBpcod5A8',
    appId: '1:379423361798:web:fbc6e8b2dc2bf06ba46c87',
    messagingSenderId: '379423361798',
    projectId: 'mymeals-flutter-project',
    authDomain: 'mymeals-flutter-project.firebaseapp.com',
    storageBucket: 'mymeals-flutter-project.appspot.com',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyCjKX0y1YcEZ3mMejrk704NsGEKbR_vYSI',
    appId: '1:379423361798:android:553081e009d6004ea46c87',
    messagingSenderId: '379423361798',
    projectId: 'mymeals-flutter-project',
    storageBucket: 'mymeals-flutter-project.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyA-JfkN8TdCbQfDtcL4dCjF1b5jrEe91l8',
    appId: '1:379423361798:ios:73aacdeb6a07d5b0a46c87',
    messagingSenderId: '379423361798',
    projectId: 'mymeals-flutter-project',
    storageBucket: 'mymeals-flutter-project.appspot.com',
    iosClientId: '379423361798-tkab41d5rdss1p2l6d6rt2oqon20q389.apps.googleusercontent.com',
    iosBundleId: 'com.daniel.mymeals',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyA-JfkN8TdCbQfDtcL4dCjF1b5jrEe91l8',
    appId: '1:379423361798:ios:30a33bb91335dca9a46c87',
    messagingSenderId: '379423361798',
    projectId: 'mymeals-flutter-project',
    storageBucket: 'mymeals-flutter-project.appspot.com',
    iosClientId: '379423361798-becovtpch3o7atoiid4p7tgvmga902gp.apps.googleusercontent.com',
    iosBundleId: 'com.daniel.mymeals.RunnerTests',
  );
}
